server:
  port: 8083
#rocketmq配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
    max-message-size: 4194304
spring:
  #nacos配置
  application:
    name: loggingservice
  cloud:
    nacos:
      server-addr: localhost:8848
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/logs_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
